# Generated by Django 3.1.1 on 2021-03-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_auto_20210322_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='num_interested',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
