# Generated by Django 3.1.4 on 2021-03-22 07:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guest.users')),
            ],
            options={
                'db_table': 'Administrators',
            },
            bases=('guest.users',),
        ),
        migrations.CreateModel(
            name='Organizers',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guest.users')),
            ],
            options={
                'db_table': 'Organizers',
            },
            bases=('guest.users',),
        ),
        migrations.AlterField(
            model_name='users',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 22, 15, 59, 51, 977608)),
        ),
    ]
