# Generated by Django 3.1.4 on 2021-03-21 03:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 21, 11, 34, 55, 181554)),
        ),
        migrations.CreateModel(
            name='currentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users', to='guest.users')),
            ],
        ),
    ]
