# Generated by Django 3.1.4 on 2021-03-21 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_auto_20210321_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentuser',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='users',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 21, 11, 40, 21, 701700)),
        ),
    ]
