# Generated by Django 3.1.4 on 2021-03-21 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_auto_20210321_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentuser',
            name='user',
        ),
        migrations.AddField(
            model_name='currentuser',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 21, 11, 43, 1, 230262)),
        ),
    ]
