# Generated by Django 3.1.4 on 2021-03-23 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0006_auto_20210323_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 23, 14, 19, 44, 91665)),
        ),
    ]
