# Generated by Django 3.1.1 on 2021-03-22 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0006_auto_20210322_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 23, 1, 58, 33, 946044)),
        ),
    ]
