# Generated by Django 3.1.4 on 2021-03-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='num_interested',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='num_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
