# Generated by Django 3.1.4 on 2021-03-23 03:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0006_auto_20210323_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(blank=True, max_length=255, null=True)),
                ('notif_date', models.DateField(default=datetime.datetime(2021, 3, 23, 11, 38, 0, 186389))),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receiver_Users', to='guest.users')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender_Users', to='guest.users')),
            ],
            options={
                'db_table': 'notif',
            },
        ),
    ]
