# Generated by Django 3.1.4 on 2021-03-23 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_auto_20210322_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 23, 11, 38, 0, 186389)),
        ),
    ]
