# Generated by Django 3.1.1 on 2021-03-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0007_auto_20210323_0158'),
        ('guest', '0007_auto_20210323_1419'),
    ]

    operations = [
    ]
