# Generated by Django 3.1.4 on 2021-03-22 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0003_auto_20210322_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_type', models.CharField(blank=True, max_length=10, null=True)),
                ('letter', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users', to='guest.users')),
            ],
            options={
                'db_table': 'Requests',
            },
        ),
    ]
