# Generated by Django 3.1.4 on 2021-03-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='pending',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
