# Generated by Django 3.1.4 on 2021-03-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210322_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='pending',
            field=models.IntegerField(default=0),
        ),
    ]
