# Generated by Django 3.1.4 on 2021-03-23 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_auto_20210322_2040'),
        ('guest', '0007_auto_20210323_1419'),
        ('user', '0004_auto_20210322_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Events', to='organizer.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Participants', to='guest.users')),
            ],
            options={
                'db_table': 'Participants',
            },
        ),
    ]
